In [1]:
import pandas as pd

In [60]:
from tqdm import tqdm #used for progress bar when ingesting the data into db in batches

In [ ]:
from sqlalchemy import create_engine #used to ingest data from dataframe to db

In [8]:
green_taxi_prefix = 'https://d37ci6vzurychx.cloudfront.net/trip-data'
green_taxi_url=f'{green_taxi_prefix}/green_tripdata_2025-11.parquet'

green_taxi_url

'https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet'

In [13]:
zones_prefix='https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc'
zones_url=f'{zone_prefix}/taxi_zone_lookup.csv'

zones_url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [11]:
gt_df = pd.read_parquet(green_taxi_url)

In [12]:
gt_df.head() #NOT REQUIRED ON THE SCRIPT

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [14]:
z_df=pd.read_csv(zones_url)

In [15]:
z_df.head() #NOT REQUIRED ON THE SCRIPT

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [18]:
gt_df.info() #NOT REQUIRED ON THE SCRIPT to get the schema in the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46912 entries, 0 to 46911
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               46912 non-null  int32
 1   lpep_pickup_datetime   46912 non-null  datetime64[us]
 2   lpep_dropoff_datetime  46912 non-null  datetime64[us]
 3   store_and_fwd_flag     41343 non-null  object
 4   RatecodeID             41343 non-null  float64
 5   PULocationID           46912 non-null  int32
 6   DOLocationID           46912 non-null  int32
 7   passenger_count        41343 non-null  float64
 8   trip_distance          46912 non-null  float64
 9   fare_amount            46912 non-null  float64
 10  extra                  46912 non-null  float64
 11  mta_tax                46912 non-null  float64
 12  tip_amount             46912 non-null  float64
 13  tolls_amount           46912 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  46912 non-null  float64
 16  total_amount           46912 non-null  float64
 17  payment_type           41343 non-null  float64
 18  trip_type              41342 non-null  float64
 19  congestion_surcharge   41343 non-null  float64
 20  cbd_congestion_fee     46912 non-null  float64
dtypes: datetime64[us](2), float64(15), int32(3), object(1)
memory usage: 7.0+ MB

In [19]:
z_df.info() #NOT REQUIRED ON THE SCRIPT  to get the schema in the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    object
 2   Zone          264 non-null    object
 3   service_zone  263 non-null    object
dtypes: int64(1), object(3)
memory usage: 8.4+ KB

In [20]:
engine = create_engine('postgresql://root:root@localhost:5432/green_taxi') #create database connection

In [27]:
print(pd.io.sql.get_schema(gt_df, name='green_taxi', con=engine)) #NOT REQUIRED ON THE SCRIPT to get the schema to be created in db

CREATE TABLE green_taxi (
	"VendorID" INTEGER,
	lpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	lpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	store_and_fwd_flag TEXT,
	"RatecodeID" FLOAT(53),
	"PULocationID" INTEGER,
	"DOLocationID" INTEGER,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53),
	cbd_congestion_fee FLOAT(53)
)

In [30]:
gt_df.head(0).to_sql(name='green_taxi', con=engine, if_exists='replace') #.head(0) to install just the schema to db without any data yet

0

In [28]:
print(pd.io.sql.get_schema(z_df, name='zones', con=engine)) #NOT REQUIRED ON THE SCRIPT to get the schema to be created in db

CREATE TABLE zones (
	"LocationID" BIGINT,
	"Borough" TEXT,
	"Zone" TEXT,
	service_zone TEXT
)

In [31]:
z_df.head(0).to_sql(name='zones', con=engine, if_exists='replace') #.head(0) to install just the schema to db without any data yet

0

In [63]:
#To add ingest the data in chunks for parquet format
chunk_size=1000

for i in tqdm(range(0, len(gt_df), chunk_size)):
    gt_df_chunk = gt_df.iloc[i:i + chunk_size]
    gt_df_chunk.to_sql(name='green_taxi', con=engine, if_exists='append', index=False)

100%|███████████████████████████████████████████████████████████████| 47/47 [00:04<00:00, 11.18it/s]

In [67]:
#To add ingest the data in chunks for parquet format
z_chunk_size=50

for i in tqdm(range(0, len(z_df), z_chunk_size)):
    z_df_chunk = z_df.iloc[i:i + z_chunk_size]
    z_df_chunk.to_sql(name='zones', con=engine, if_exists='append', index=False)

100%|████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 203.68it/s]

In [73]:
df_result= pd.read_sql("SELECT * FROM green_taxi limit 10", con=engine)
df_result

,index,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,None,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,...,0.5,1.94,0.0,None,1.0,11.64,1.0,1.0,0.00,0.00
1,None,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,...,0.5,0.00,0.0,None,1.0,9.70,2.0,1.0,0.00,0.00
2,None,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,...,0.5,5.00,0.0,None,1.0,21.00,1.0,1.0,0.00,0.00
3,None,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,...,0.5,0.50,0.0,None,1.0,27.70,1.0,1.0,0.00,0.00
4,None,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,...,1.5,1.00,0.0,None,1.0,24.65,1.0,1.0,2.75,0.00
5,None,1,2025-11-01 00:42:13,2025-11-01 01:04:50,N,1.0,112,48,2.0,5.10,...,1.5,6.55,0.0,None,1.0,39.35,1.0,1.0,2.75,0.75
6,None,2,2025-11-01 00:05:41,2025-11-01 00:39:20,N,1.0,83,87,1.0,9.80,...,0.5,9.92,0.0,None,1.0,59.52,1.0,1.0,2.75,0.75
7,None,2,2025-11-01 00:42:14,2025-11-01 01:13:20,N,1.0,66,233,1.0,5.01,...,0.5,6.98,0.0,None,1.0,41.88,1.0,1.0,2.75,0.75
8,None,2,2025-11-01 00:03:08,2025-11-01 00:06:27,N,1.0,223,223,1.0,0.63,...,0.5,1.52,0.0,None,1.0,9.12,1.0,1.0,0.00,0.00
9,None,2,2025-11-01 00:56:33,2025-11-01 01:01:34,N,1.0,130,130,1.0,1.15,...,0.5,0.00,0.0,None,1.0,10.40,2.0,1.0,0.00,0.00

In [74]:
z_df_result= pd.read_sql("SELECT * FROM zones limit 10", con=engine)
z_df_result

   index  LocationID        Borough                     Zone service_zone
0      0           1            EWR           Newark Airport          EWR
1      1           2         Queens              Jamaica Bay    Boro Zone
2      2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3      3           4      Manhattan            Alphabet City  Yellow Zone
4      4           5  Staten Island            Arden Heights    Boro Zone
5      5           6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6      6           7         Queens                  Astoria    Boro Zone
7      7           8         Queens             Astoria Park    Boro Zone
8      8           9         Queens               Auburndale    Boro Zone
9      9          10         Queens             Baisley Park    Boro Zone

In [80]:
#Question 3
df_result= pd.read_sql("SELECT COUNT(1) FROM green_taxi WHERE trip_distance <=1 AND lpep_pickup_datetime BETWEEN '2025-11-01' AND '2025-12-01'", con=engine)
df_result

   count
0   8007

In [87]:
#Question 4
df_result1=pd.read_sql("SELECT lpep_pickup_datetime, trip_distance FROM green_taxi WHERE trip_distance <= 100 ORDER BY trip_distance DESC LIMIT 1", con=engine)
df_result1

  lpep_pickup_datetime  trip_distance
0  2025-11-14 15:36:27          88.03

In [114]:
#Question 5
df_result2 = pd.read_sql('SELECT z."Zone", SUM(gt.total_amount) FROM green_taxi AS gt INNER JOIN zones AS z ON CAST(gt."PULocationID" AS BIGINT) = z."LocationID" WHERE DATE(gt.lpep_pickup_datetime)=\'2025-11-18\' GROUP BY z."Zone" ORDER BY SUM(gt.total_amount) DESC', con=engine)
df_result2

                                  Zone       sum
0                    East Harlem North  18563.84
1                    East Harlem South  13392.26
2                         Central Park   4757.58
3             Washington Heights South   4278.10
4                  Morningside Heights   4201.18
..                                 ...       ...
132              Upper West Side South     32.00
133                       West Village     32.00
134  East New York/Pennsylvania Avenue     32.00
135                          Bronxdale     27.14
136                 Brooklyn Navy Yard      0.00

[137 rows x 2 columns]

In [122]:
#Question 6 --TO BE DELETED
query="""
WITH pu_largest_tip AS (
    SELECT MAX(gt.tip_amount) AS largest_tip
    FROM green_taxi AS gt
    INNER JOIN zones AS z
    ON gt."PULocationID"=z."LocationID"
    WHERE z."Zone"=\'East Harlem North\'
    AND TO_CHAR(gt."lpep_pickup_datetime", \'YYYY-MM\') = \'2025-11\'
)

SELECT 
    z."Zone" AS DO_Zone,
    gt.tip_amount
FROM green_taxi gt
INNER JOIN zones z
ON gt."DOLocationID" = z."LocationID"
WHERE gt.tip_amount = (
    SELECT pu.largest_tip
    FROM pu_largest_tip AS pu
)
"""
df_result2 = pd.read_sql(query, con=engine)
df_result2

          do_zone  tip_amount
0  Yorkville West       81.89
1  Yorkville West       81.89

In [127]:
#Question 6 --TO BE DELETED
query="""
WITH pu_largest_tip AS (
    SELECT MAX(gt.tip_amount) AS largest_tip
    FROM green_taxi gt
    INNER JOIN zones z
    ON gt."PULocationID"=z."LocationID"
    WHERE z."Zone"=\'East Harlem North\'
    AND TO_CHAR(gt."lpep_pickup_datetime", \'YYYY-MM\') = \'2025-11\'
),
do_location AS (
    SELECT 
    gt."DOLocationID" as do_locationId
    FROM green_taxi gt
    WHERE gt.tip_amount = (
        SELECT pu.largest_tip
        FROM pu_largest_tip AS pu
    )
)
SELECT 
z."Zone"
FROM zones z
WHERE z."LocationID"= (SELECT do_locationId FROM do_location)
"""
df_result2 = pd.read_sql(query, con=engine)
df_result2

             Zone
0  Yorkville West
1  Yorkville West

In [130]:
#Question 6
query="""
WITH pu_largest_tip AS (
    SELECT MAX(gt.tip_amount) AS largest_tip_amount
    FROM green_taxi AS gt
    INNER JOIN zones AS z
    ON gt."PULocationID"=z."LocationID"
    WHERE z."Zone"=\'East Harlem North\'
    AND TO_CHAR(gt."lpep_pickup_datetime", \'YYYY-MM\') = \'2025-11\'
)

SELECT 
    z."Zone" AS DO_Zone,
    gt.tip_amount
FROM green_taxi gt
INNER JOIN zones z
ON gt."DOLocationID" = z."LocationID"
INNER JOIN pu_largest_tip lt
ON lt.largest_tip_amount = gt.tip_amount

"""
df_result2 = pd.read_sql(query, con=engine)
df_result2

          do_zone  tip_amount
0  Yorkville West       81.89
1  Yorkville West       81.89